### ISSUE TITLE
Invalid redirect_uri

### ISSUE THREAD

**Issue by davidlesches** [l1h3r/omniauth-infusionsoft#1]
I keep getting {"error":"invalid_request","error_description":"Invalid redirect_uri"} no matter what I do, even using https and ensuring the redirect url in the Infusionsoft/Mashery app setting matches example.com/auth/infusionsoft/callback

Did you run into this? Any ideas?

**Comment by L1h3r** [comment]
The ```redirect_uri``` has to be a url in your application

**Comment by Andsbf** [comment]
Hi davidlesches,
did you find a solution for this ?

Regards,

**Comment by davidlesches** [comment]
No. I tried for hours and hours and went crazy, convinced I was missing something. Eventually I gave up and just used the standard OAuth gem (https://github.com/intridea/oauth2) to roll a regular implementation and it worked flawlessly. So there is something wrong with the strategy in this gem, and I tried finding it, but I couldn't. It clearly does work for most people as-is. If you're having the same issue I was having, I'd recommend just using the oauth2 gem.

**Comment by Andsbf** [comment]
davidlesches, I've managed to solve the problem, I had to add this "OmniAuth.config.full_host = "https://YOUR_LOCALHOST.FOOL.BAR"" to the development environment(development.rb).

Apparently  in response Omniauth included port used internally by nginx. You can read more about it here (http://awesomeprogrammer.com/blog/2012/12/09/dealing-with-omniauth-redirect-uri-mismatch-invalid-port-number-gotcha/).

**Comment by davidlesches** [comment]
Thanks!
